apiVersion: v1
baseDomain: PROVIDE_BASEDOMAIN
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
metadata:
  name: PROVIDE_CLUSTERNAME
networking:
  clusterNetwork:
  - cidr: PROVIDE_CLUSTERNETWORKCIDR #10.128.0.0/16
    hostPrefix: 23
  machineNetwork:
  - cidr: PROVIDE_MACHINENETWORKCIDR #192.168.1.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - PROVIDE_SERVICENETWORKCIDR #172.30.0.0/16
platform:
  none: {}
bootstrapInPlace:
  installationDisk: PROVIDE_INSTALLATIONDISK #/dev/sda
pullSecret: 'INSERT_QUAY_PULL_SECRET'
sshKey: |
  INSERT_SSH_PUBLICKEY
